language: node_js
node_js: "10"

matrix:
  env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

  include:
    - os: windows
    - os: osx
      osx_image: xcode9.4

    - os: linux
      services: docker
      language: generic
      before_install:
        - sudo apt-get install -y libxml2-dev
        - apt-get install fakeroot

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-forge

install:
  - npm install
  - npm update

script:
  - npm run make
