language: node_js
node_js: "10"

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      before_deploy:
        - zip -rj blink-darwin-x64.zip installer
      deploy:
        provider: releases
        api_key: $ghreleases
        file: blink-darwin-x64.zip
        skip_cleanup: true
    - os: linux
      services: docker
      language: generic
      before_install:
        - sudo apt-get install -y libxml2-dev
        - sudo apt-get install fakeroot
        - sudo apt-get install rpm
      before_deploy:
        - zip -r blink-linux-x64.zip -i blink-linux-x64
      deploy:
        provider: releases
        api_key: $ghreleases
        file: blink-linux-x64.zip
        skip_cleanup: true

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

install:
  - package_version=$(node -p -e "require('./package.json').version")
  - npm install
  - npm update

script:
  - npm run compile
  - rm -rf src
  - npm run package
  - npm run installer
  - git tag v$package_version
