language: node_js
node_js: "10"

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-forge

before_install:
  - sudo apt-get install -y libxml2-dev

install:
  - npm install
  - npm update

script:
  - npm run make
