language: node_js
node_js: "10"

branches:
  only:
    - master

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      deploy:
        provider: releases
        api_key: $env:ghreleases
        file: blink-darwin-x64
        skip_cleanup: true
    - os: linux
      services: docker
      language: generic
      before_install:
        - sudo apt-get install -y libxml2-dev
        - sudo apt-get install fakeroot
        - sudo apt-get install rpm
      deploy:
        provider: releases
        api_key: $env:ghreleases
        file: blink-linux-x64
        skip_cleanup: true

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

install:
  - npm install
  - npm update

script:
  - npm run dist
