language: node_js
node_js: "10"

branches:
  only:
    - master

matrix:
  include:
    # - os: osx
    #   osx_image: xcode9.4
    # - os: linux
    #   services: docker
    #   language: generic
    #   before_install:
    #     - sudo apt-get install -y libxml2-dev
    #     - sudo apt-get install fakeroot
    #     - sudo apt-get install rpm
    # - os: windows

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

install:
  - npm install
  - npm update

script:
  - travis_wait npm run dist
