language: node_js
node_js: "10"

branches:
  only:
    - master

env:
  - PACKAGE_VERSION="1.0.*"

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      before_deploy:
        - zip -r blink-darwin-x64.zip blink-darwin-x64
        - git tag darwin-$PACKAGE_VERSION
      deploy:
        provider: releases
        api_key: $ghreleases
        file: blink-darwin-x64.zip
        skip_cleanup: true
    - os: linux
      services: docker
      language: generic
      before_install:
        - sudo apt-get install -y libxml2-dev
        - sudo apt-get install fakeroot
        - sudo apt-get install rpm
      before_deploy:
        - zip -r blink-linux-x64.zip blink-linux-x64
        - git tag linux-$PACKAGE_VERSION
      deploy:
        provider: releases
        api_key: $ghreleases
        file: blink-linux-x64.zip
        skip_cleanup: true

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

install:
  - npm install
  - npm update

script:
  - npm run build
  - npm run dist
