environment:
  nodejs_version: "10"

branches:
  only:
    - master

artifacts:
  - path: installer/Setup.exe
    name: blink-win32-x64.exe

install:
  - ps: Install-Product node $env:nodejs_version $env:node_platform
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - npm install
  - npm update

test_script:
  - node --version
  - npm --version

build_script:
  - npm run build
  - rm -rf src
  - npm run dist
  - npm run setup-win

deploy:
  provider: GitHub
  auth_token: "%ghreleases%"
  tag: "v%package_version%"
