environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version $env:node_platform
  - npm install

test_script:
  - node --version
  - npm --version

build_script:
  - npm run dist
