environment:
  nodejs_version: "10"

branches:
  only:
    - master

artifacts:
  - path: blink-win32-x64
    name: blink-windows

install:
  - ps: Install-Product node $env:nodejs_version $env:node_platform
  - npm install
  - npm update

test_script:
  - node --version
  - npm --version

build_script:
  - npm run build
  - npm run dist

deploy:
  provider: GitHub
  auth_token: $env:github_releases
