environment:
  nodejs_version: "10"

branches:
  only:
    - master

artifacts:
  - path: blink-win32-x64

install:
  - ps: Install-Product node $env:nodejs_version $env:node_platform
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - npm install
  - npm update

test_script:
  - node --version
  - npm --version

build_script:
  - npm run build
  - rm -rf src
  - npm run dist

deploy:
  provider: GitHub
  auth_token: "%ghreleases%"
  tag: "%package_version%"
